### ISSUE TITLE
Releases and versions, plus update instructions

### ISSUE THREAD

**Issue by syntaxerror** [Kasseservice/woocommerce-3x#1]
It would be quite useful if you did create new releases having version numbers (also in code and module display).

Quite often people will not know which version they have installed in their store, and both them and you will struggle figuring out if they have a known bug already being fixed in a newer revision.

Also the commits log has quite limited comments, not always telling clearly what was fixed or changed, so adding releases with this more clearly listed would be better.

And last, but not least, adding update instructions would make it clear if there is something special to be aware of or not.

**Comment by kgpanteon** [comment]
Thanks for suggestion. We will make release notes and version update feature including migration notes.

**Comment by christiaangieles** [comment]
I'd also include some automagical updating on the WordPress front. AFAIK everything needs to be manually updated now?
