### ISSUE TITLE
2 woocommerce stores sync

### ISSUE THREAD

**Issue by kabubi** [Kasseservice/woocommerce-3x#2]
I'm trying to synchronize my 2 online stores with my pos but only one is synchronized. All credentials are correct. Can this be done? Is there any special configuration? thank you.

**Comment by kgpanteon** [comment]
You can use same plugin and same credential to multiple webshops. Please update plugin with latest one and update setting once again.

**Comment by kabubi** [comment]
Thanks, let me test if that's the problem.

**Comment by kabubi** [comment]
I updated the plugin with the new files but it still doesn't work (it only works on one site), maybe it has something bad configured?
Attached capture of my configuration.
Thanks
https://imgur.com/PxOBzKW

**Comment by kgpanteon** [comment]
As per log, I can see everything is working. What type of issue exactly you are facing?

**FYI:** For stock update, Woocommerce SKU and Duell Varenr(product number) must be match. Also plugin maintaining last updated datetime cron runs in wordpress database.

**Comment by kabubi** [comment]
I adjust this:
FYI: For stock update, Woocommerce SKU and Duell Varenr(product number) must be match. Also plugin maintaining last updated datetime cron runs in wordpress database.
and it still doesn't work, the stock doesn't synchronize.
New log: https://drive.google.com/file/d/1wMbQ68e6ZKmiFy2Q7Qp06NVt64guYQx0/view?usp=sharing
Thanks

**Comment by kgpanteon** [comment]
Please contact on email support api@kasseservice.no.
Log files content shows no errors.

**Comment by syntaxerror** [comment]
Note that the log file includes your credentials, and thus can be used by someone who would like to mess with your system/account. You should remove this info from public, and also regenerate your credentials ...

Think security!
